name: Deploy React to VPS

on:
  push:
    branches:
      - main  # Ganti dengan 'master' jika branch utama Anda master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VPS using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          # Arahkan ke folder project di VPS
          cd /var/www/stg.youvitation.com/frontend
          
          # Tarik perubahan terbaru
          echo "Melakukan Git Pull..."
          git pull origin main
          
          # Install dependencies (jika ada paket baru)
          echo "Install Dependencies..."
          npm install
          
          # Build project
          echo "Building React App..."
          npm run build
          
          # (Opsional) Restart Web Server jika diperlukan konfigurasinya
          # sudo systemctl reload nginx